-- Glowi seed · curated product catalog + concern mappings
-- Real products, realistic prices (USD, approximate retail), stable retailer
-- search links (never 404). image_url intentionally null — the app renders
-- branded gradient cards. Idempotent.

delete from public.product_concerns;
delete from public.products;

insert into public.products
  (slug, brand, name, category, description, key_ingredients, price_usd, retailer_links, skin_types, am_pm, step_order)
values
-- ─────────────── Cleansers ───────────────
('cerave-foaming-cleanser','CeraVe','Foaming Facial Cleanser','cleanser',
 'Gel cleanser that removes oil without stripping; the default pick for oily, breakout-prone skin.',
 array['niacinamide','ceramides','hyaluronic acid'],15.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+foaming+facial+cleanser"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cerave%20foaming%20facial%20cleanser"}]',
 array['oily','combination'],'both',10),
('cerave-hydrating-cleanser','CeraVe','Hydrating Facial Cleanser','cleanser',
 'Creamy non-foaming cleanser that respects the moisture barrier; ideal when skin feels tight after washing.',
 array['ceramides','glycerin','hyaluronic acid'],15.49,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+hydrating+facial+cleanser"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=cerave+hydrating+cleanser"}]',
 array['dry','normal','sensitive'],'both',10),
('lrp-toleriane-cleanser','La Roche-Posay','Toleriane Hydrating Gentle Cleanser','cleanser',
 'Milky cleanser built for reactive skin — cleans thoroughly with close to zero sting risk.',
 array['ceramide-3','niacinamide','glycerin'],16.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=la+roche+posay+toleriane+hydrating+gentle+cleanser"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=toleriane%20hydrating%20cleanser"}]',
 array['dry','sensitive','normal'],'both',10),
('vanicream-gentle-cleanser','Vanicream','Gentle Facial Cleanser','cleanser',
 'Free of fragrance, dyes, and common irritants; dermatologist staple for eczema-prone faces.',
 array['glycerin','coco-glucoside'],8.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=vanicream+gentle+facial+cleanser"},{"retailer":"Walmart","url":"https://www.walmart.com/search?q=vanicream+gentle+facial+cleanser"}]',
 array['sensitive','dry','normal'],'both',10),
('cerave-sa-cleanser','CeraVe','SA Smoothing Cleanser','cleanser',
 'Salicylic-acid cleanser that exfoliates inside the pore while you wash — congestion control on autopilot.',
 array['salicylic acid','ceramides','hyaluronic acid'],14.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+sa+smoothing+cleanser"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cerave%20sa%20cleanser"}]',
 array['oily','combination'],'both',10),
('cosrx-low-ph-cleanser','COSRX','Low pH Good Morning Gel Cleanser','cleanser',
 'Mildly acidic gel that cleans oily skin without disrupting the acid mantle; cult K-beauty morning staple.',
 array['tea tree oil','betaine salicylate'],11.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cosrx+low+ph+good+morning+cleanser"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cosrx%20low%20ph%20cleanser"}]',
 array['oily','combination','normal'],'am',10),
('yttp-superfood-cleanser','Youth To The People','Superfood Antioxidant Cleanser','cleanser',
 'Antioxidant-packed gel that leaves dull skin notably brighter-looking; removes makeup cleanly.',
 array['kale extract','green tea','vitamin C'],39.00,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=youth%20to%20the%20people%20superfood%20cleanser"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=youth+to+the+people+superfood+cleanser"}]',
 array['normal','combination','oily'],'both',10),
('cetaphil-gentle-cleanser','Cetaphil','Gentle Skin Cleanser','cleanser',
 'The classic do-no-harm cleanser; a safe baseline while skin recovers from irritation or flares.',
 array['glycerin','panthenol','niacinamide'],11.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cetaphil+gentle+skin+cleanser"},{"retailer":"Walgreens","url":"https://www.walgreens.com/search/results.jsp?Ntt=cetaphil%20gentle%20skin%20cleanser"}]',
 array['sensitive','dry','normal'],'both',10),

-- ─────────────── Exfoliants ───────────────
('paulas-choice-2-bha','Paula''s Choice','Skin Perfecting 2% BHA Liquid Exfoliant','exfoliant',
 'The benchmark leave-on BHA: dissolves blackheads and smooths texture with minimal irritation.',
 array['salicylic acid','green tea extract'],35.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=paulas+choice+2%25+bha+liquid+exfoliant"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=paulas%20choice%20bha"}]',
 array['oily','combination','normal'],'pm',20),
('to-glycolic-toner','The Ordinary','Glycolic Acid 7% Exfoliating Toner','exfoliant',
 'Budget AHA toner that restores glow within weeks; start two nights a week.',
 array['glycolic acid','aloe vera','ginseng'],13.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+glycolic+acid+7+toning+solution"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20glycolic%20acid"}]',
 array['normal','combination','oily'],'pm',20),
('to-lactic-acid-10','The Ordinary','Lactic Acid 10% + HA','exfoliant',
 'Gentler large-molecule AHA paired with hyaluronic acid; resurfaces with less sting than glycolic.',
 array['lactic acid','hyaluronic acid','tasmanian pepperberry'],14.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+lactic+acid+10+ha"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=the%20ordinary%20lactic%20acid"}]',
 array['dry','normal','sensitive'],'pm',20),
('to-aha-bha-peel','The Ordinary','AHA 30% + BHA 2% Peeling Solution','exfoliant',
 'The famous red peel — a once-weekly, 10-minute professional-strength resurfacer. Experienced users only.',
 array['glycolic acid','lactic acid','salicylic acid'],9.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+peeling+solution"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20peeling%20solution"}]',
 array['normal','combination','oily'],'pm',70),
('inkey-pha-toner','The INKEY List','PHA Gentle Exfoliating Toner','exfoliant',
 'Polyhydroxy acids exfoliate at the surface only — the entry point for sensitive skin that wants glow.',
 array['PHA 3%','niacinamide','aloe'],12.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=inkey+list+pha+toner"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=inkey%20list%20pha%20toner"}]',
 array['sensitive','dry','normal'],'pm',20),

-- ─────────────── Serums & treatments ───────────────
('to-niacinamide','The Ordinary','Niacinamide 10% + Zinc 1%','serum',
 'The best-selling oil-control serum on earth: shrinks the look of pores and calms breakouts for pocket change.',
 array['niacinamide','zinc PCA'],6.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+niacinamide+10+zinc"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20niacinamide"}]',
 array['oily','combination','normal'],'both',30),
('to-hyaluronic','The Ordinary','Hyaluronic Acid 2% + B5','serum',
 'Multi-weight hyaluronic acid that pulls water into dehydrated skin; apply on damp skin and seal.',
 array['hyaluronic acid','vitamin B5'],8.90,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+hyaluronic+acid+2+b5"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=the%20ordinary%20hyaluronic%20acid"}]',
 array['dry','normal','combination','sensitive'],'both',30),
('to-azelaic','The Ordinary','Azelaic Acid Suspension 10%','treatment',
 'Multitasker that fades post-acne marks and calms redness — one of the few actives rosacea-prone skin loves.',
 array['azelaic acid'],11.90,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+azelaic+acid+suspension"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20azelaic%20acid"}]',
 array['normal','combination','sensitive','oily'],'pm',35),
('to-alpha-arbutin','The Ordinary','Alpha Arbutin 2% + HA','serum',
 'Targeted tyrosinase inhibitor that fades dark spots gradually without irritation.',
 array['alpha arbutin','hyaluronic acid'],10.90,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+alpha+arbutin"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=the%20ordinary%20alpha%20arbutin"}]',
 array['normal','dry','oily','combination'],'both',30),
('lrp-effaclar-duo','La Roche-Posay','Effaclar Duo Acne Treatment','treatment',
 'Micronized 5.5% benzoyl peroxide that kills acne bacteria fast with less of the classic BPO dryness.',
 array['benzoyl peroxide 5.5%','LHA','glycerin'],31.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=la+roche+posay+effaclar+duo"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=effaclar%20duo"}]',
 array['oily','combination','normal'],'pm',35),
('pc-azelaic-booster','Paula''s Choice','10% Azelaic Acid Booster','treatment',
 'Elegant cream-gel azelaic formula targeting redness and lingering marks; layers under moisturizer.',
 array['azelaic acid','salicylic acid','licorice root'],38.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=paulas+choice+azelaic+acid+booster"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=paulas%20choice%20azelaic"}]',
 array['sensitive','normal','combination'],'pm',35),
('differin-gel','Differin','Adapalene Gel 0.1%','treatment',
 'Prescription-strength retinoid, now OTC — the single most evidence-backed step for recurring acne.',
 array['adapalene 0.1%'],14.88,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=differin+adapalene+gel"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=differin+gel"}]',
 array['oily','combination','normal'],'pm',40),
('inkey-retinol','The INKEY List','Retinol Serum','treatment',
 'Slow-release 1% retinol equivalent with squalane buffering — a forgiving first retinoid for lines.',
 array['retinol','squalane'],12.99,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=inkey%20list%20retinol"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=inkey+list+retinol+serum"}]',
 array['normal','dry','combination'],'pm',40),
('cerave-resurfacing-retinol','CeraVe','Resurfacing Retinol Serum','treatment',
 'Encapsulated retinol aimed at post-acne marks and enlarged pores, cushioned with ceramides.',
 array['encapsulated retinol','niacinamide','ceramides'],19.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+resurfacing+retinol+serum"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cerave%20resurfacing%20retinol"}]',
 array['oily','combination','normal'],'pm',40),
('roc-deep-wrinkle-night','RoC','Retinol Correxion Deep Wrinkle Night Cream','treatment',
 'Drugstore retinol night cream with decades of clinical receipts on established wrinkles.',
 array['retinol','glycolic acid'],24.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=roc+retinol+correxion+deep+wrinkle+night+cream"},{"retailer":"Walmart","url":"https://www.walmart.com/search?q=roc+deep+wrinkle+night+cream"}]',
 array['normal','dry'],'pm',40),
('timeless-vit-c','Timeless','20% Vitamin C + E Ferulic Acid Serum','serum',
 'The famous L-ascorbic acid formula at a fraction of the prestige price; brightens and defends.',
 array['vitamin C 20%','vitamin E','ferulic acid'],31.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=timeless+20+vitamin+c+e+ferulic+acid"},{"retailer":"Timeless","url":"https://www.timelessha.com/collections/serum"}]',
 array['normal','oily','combination'],'am',30),
('maelove-glow-maker','Maelove','The Glow Maker','serum',
 'Beloved vitamin C serum praised for SkinCeuticals-like results with a gentler feel.',
 array['vitamin C 15%','vitamin E','ferulic acid','hyaluronic acid'],36.00,
 '[{"retailer":"Maelove","url":"https://www.maelove.com/products/glow-maker"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=maelove+glow+maker"}]',
 array['normal','dry','combination','sensitive'],'am',30),
('skinceuticals-ce-ferulic','SkinCeuticals','C E Ferulic','serum',
 'The gold-standard antioxidant serum with the original patented formula — the splurge that earns it.',
 array['vitamin C 15%','vitamin E 1%','ferulic acid 0.5%'],182.00,
 '[{"retailer":"Dermstore","url":"https://www.dermstore.com/search?q=skinceuticals%20ce%20ferulic"},{"retailer":"SkinCeuticals","url":"https://www.skinceuticals.com/c-e-ferulic-635494263008.html"}]',
 array['normal','dry'],'am',30),
('good-molecules-discoloration','Good Molecules','Discoloration Correcting Serum','serum',
 'Tranexamic acid + niacinamide pairing that quietly outperforms its price on stubborn dark patches.',
 array['tranexamic acid 3%','niacinamide 4%'],14.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=good+molecules+discoloration+correcting+serum"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=good%20molecules%20discoloration"}]',
 array['normal','oily','combination','dry'],'both',30),
('cosrx-snail-essence','COSRX','Advanced Snail 96 Mucin Power Essence','serum',
 'Viral hydrating essence that plumps dull, dehydrated skin and supports healing of post-blemish marks.',
 array['snail secretion filtrate 96%'],17.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cosrx+snail+mucin+96+essence"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cosrx%20snail%20mucin"}]',
 array['dry','normal','combination','sensitive'],'both',28),
('boj-glow-serum','Beauty of Joseon','Glow Serum: Propolis + Niacinamide','serum',
 'Honey-textured K-beauty serum that calms breakouts while adding the glassy glow it''s named for.',
 array['propolis 60%','niacinamide 2%'],17.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=beauty+of+joseon+glow+serum"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=beauty%20of%20joseon%20glow%20serum"}]',
 array['combination','oily','normal'],'both',30),
('hada-labo-premium-lotion','Hada Labo','Gokujyun Premium Hydrating Lotion','serum',
 'Japanese hydrating lotion with five forms of hyaluronic acid; the dehydration fix in one watery step.',
 array['hyaluronic acid x5','urea'],17.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=hada+labo+gokujyun+premium+lotion"},{"retailer":"Walmart","url":"https://www.walmart.com/search?q=hada+labo+premium+lotion"}]',
 array['dry','normal','sensitive'],'both',25),
('to-salicylic-serum','The Ordinary','Salicylic Acid 2% Solution','treatment',
 'Targeted leave-on BHA for active breakouts and congested zones at a pharmacy-snack price.',
 array['salicylic acid 2%','witch hazel'],7.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+salicylic+acid+2"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20salicylic%20acid"}]',
 array['oily','combination'],'pm',35),
('to-squalane','The Ordinary','100% Plant-Derived Squalane','treatment',
 'Weightless lipid oil that mimics skin''s own sebum; seals in moisture without clogging.',
 array['squalane'],9.90,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+squalane+oil"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=the%20ordinary%20squalane"}]',
 array['dry','sensitive','normal'],'pm',65),
('pc-clinical-niacinamide-20','Paula''s Choice','CLINICAL Niacinamide 20% Treatment','treatment',
 'Max-strength niacinamide for stubborn, orange-peel pores; visible refinement in 2-4 weeks.',
 array['niacinamide 20%'],50.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=paulas+choice+niacinamide+20"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=paulas%20choice%20niacinamide%2020"}]',
 array['oily','combination','normal'],'pm',32),
('lrp-cicaplast-b5','La Roche-Posay','Cicaplast Balm B5+','treatment',
 'Barrier-repair balm that rescues over-exfoliated, flaring, or windburned skin overnight.',
 array['panthenol 5%','madecassoside','shea butter'],16.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=la+roche+posay+cicaplast+balm+b5"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cicaplast%20balm"}]',
 array['sensitive','dry'],'pm',65),
('avene-thermal-water','Avène','Thermal Spring Water Spray','treatment',
 'Mineral spring mist with published soothing effects on reactive, flushed skin; chill it for flares.',
 array['avène thermal spring water'],14.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=avene+thermal+spring+water"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=avene%20thermal%20water"}]',
 array['sensitive','normal','dry'],'both',24),

-- ─────────────── Eye care ───────────────
('to-caffeine-eye','The Ordinary','Caffeine Solution 5% + EGCG','eye-cream',
 'Concentrated caffeine that visibly deflates puffiness and lightens vascular dark circles by morning coffee time.',
 array['caffeine 5%','EGCG'],8.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+caffeine+solution+5+egcg"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20caffeine"}]',
 array['normal','dry','oily','combination','sensitive'],'am',45),
('inkey-caffeine-eye','The INKEY List','Caffeine Eye Cream','eye-cream',
 'Caffeine plus peptide in a cushioning base — dark-circle duty with a smoother texture than serums.',
 array['caffeine','Matrixyl 3000'],10.99,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=inkey%20list%20caffeine%20eye%20cream"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=inkey+list+caffeine+eye+cream"}]',
 array['normal','dry','combination'],'both',45),
('cerave-eye-repair','CeraVe','Eye Repair Cream','eye-cream',
 'Fragrance-free ceramide eye cream that brightens shadowy circles by thickening and hydrating thin skin.',
 array['ceramides','niacinamide','hyaluronic acid'],15.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+eye+repair+cream"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=cerave+eye+repair+cream"}]',
 array['dry','normal','sensitive'],'both',45),
('roc-retinol-eye','RoC','Retinol Correxion Line Smoothing Eye Cream','eye-cream',
 'Clinically tested retinol eye cream for crow''s feet — start twice weekly, the payoff is months out.',
 array['retinol','mineral complex'],23.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=roc+retinol+correxion+eye+cream"},{"retailer":"Walgreens","url":"https://www.walgreens.com/search/results.jsp?Ntt=roc%20retinol%20eye%20cream"}]',
 array['normal','dry'],'pm',45),

-- ─────────────── Moisturizers ───────────────
('cerave-moisturizing-cream','CeraVe','Moisturizing Cream','moisturizer',
 'The ceramide-rich tub that rebuilt a million barriers; rich enough for eczema, clean enough for faces.',
 array['ceramides','hyaluronic acid','MVE technology'],16.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+moisturizing+cream"},{"retailer":"Costco","url":"https://www.costco.com/CatalogSearch?keyword=cerave"}]',
 array['dry','sensitive','normal'],'both',60),
('cerave-pm-lotion','CeraVe','PM Facial Moisturizing Lotion','moisturizer',
 'Featherweight night lotion with niacinamide; the universal "just works" PM moisturizer.',
 array['niacinamide','ceramides','hyaluronic acid'],16.49,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+pm+facial+moisturizing+lotion"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=cerave+pm+lotion"}]',
 array['normal','combination','oily'],'pm',60),
('neutrogena-hydro-boost','Neutrogena','Hydro Boost Water Gel','moisturizer',
 'Bouncy gel hydration that oily skin actually enjoys wearing; layers cleanly under SPF and makeup.',
 array['hyaluronic acid','glycerin'],19.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=neutrogena+hydro+boost+water+gel"},{"retailer":"Walmart","url":"https://www.walmart.com/search?q=neutrogena+hydro+boost"}]',
 array['oily','combination','normal'],'both',60),
('lrp-toleriane-double-repair','La Roche-Posay','Toleriane Double Repair Face Moisturizer','moisturizer',
 'Prebiotic + ceramide moisturizer that restores barrier in 1 hour per its clinicals; sensitive-skin default.',
 array['ceramide-3','niacinamide','prebiotic thermal water'],21.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=la+roche+posay+toleriane+double+repair"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=toleriane%20double%20repair"}]',
 array['sensitive','normal','dry','combination'],'both',60),
('vanicream-moisturizing-cream','Vanicream','Moisturizing Cream','moisturizer',
 'Zero-frills, zero-irritants thick cream; the National Eczema Association seal is on the tub for a reason.',
 array['petrolatum','glycerin','sorbitol'],13.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=vanicream+moisturizing+cream"},{"retailer":"CVS","url":"https://www.cvs.com/search?searchTerm=vanicream+moisturizing+cream"}]',
 array['sensitive','dry'],'both',60),
('fab-ultra-repair','First Aid Beauty','Ultra Repair Cream','moisturizer',
 'Colloidal-oatmeal comfort cream for itchy, flaky, distressed skin — instant relief texture.',
 array['colloidal oatmeal','shea butter','ceramides'],38.00,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=first%20aid%20beauty%20ultra%20repair%20cream"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=first+aid+beauty+ultra+repair+cream"}]',
 array['dry','sensitive'],'both',60),
('avene-cicalfate','Avène','Cicalfate+ Restorative Protective Cream','moisturizer',
 'Recovery cream beloved by dermatologists post-procedure; calms angry red patches fast.',
 array['copper-zinc-sulfate','panthenol','thermal water'],28.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=avene+cicalfate"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=avene%20cicalfate"}]',
 array['sensitive','dry','normal'],'both',60),
('weleda-skin-food','Weleda','Skin Food Original','moisturizer',
 'The 95-year-old thick green tube that rescues weather-beaten, flaking skin overnight.',
 array['sunflower oil','chamomile','calendula'],19.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=weleda+skin+food+original"},{"retailer":"Whole Foods","url":"https://www.wholefoodsmarket.com/search?text=weleda%20skin%20food"}]',
 array['dry'],'pm',60),
('clinique-moisture-surge','Clinique','Moisture Surge 100H Auto-Replenishing Hydrator','moisturizer',
 'Glass-skin gel-cream that visibly re-plumps dull, tired skin and holds hydration through the day.',
 array['hyaluronic acid','aloe bio-ferment','caffeine'],43.00,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=clinique%20moisture%20surge"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=clinique%20moisture%20surge"}]',
 array['normal','dry','combination'],'both',60),
('olay-regenerist','Olay','Regenerist Micro-Sculpting Cream','moisturizer',
 'Peptide + niacinamide cream that has embarrassed luxury creams in blind clinical comparisons.',
 array['niacinamide','amino-peptides','hyaluronic acid'],28.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=olay+regenerist+micro+sculpting+cream"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=olay+regenerist"}]',
 array['normal','dry'],'both',60),

-- ─────────────── SPF ───────────────
('eltamd-uv-clear','EltaMD','UV Clear Broad-Spectrum SPF 46','spf',
 'The dermatologist-favorite SPF for acne-prone and sensitive skin: niacinamide inside, zero pilling.',
 array['zinc oxide 9%','niacinamide','hyaluronic acid'],43.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=eltamd+uv+clear+spf+46"},{"retailer":"Dermstore","url":"https://www.dermstore.com/search?q=eltamd%20uv%20clear"}]',
 array['oily','combination','sensitive','normal'],'am',90),
('lrp-anthelios-milk','La Roche-Posay','Anthelios Melt-in Milk SPF 60','spf',
 'High-protection chemical SPF with a genuinely pleasant milky finish; a yearly award-list regular.',
 array['avobenzone','homosalate','cell-ox shield'],36.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=la+roche+posay+anthelios+melt+in+milk+spf+60"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=anthelios%20melt%20in%20milk"}]',
 array['normal','dry','combination'],'am',90),
('supergoop-unseen','Supergoop!','Unseen Sunscreen SPF 40','spf',
 'Totally invisible gel SPF that doubles as a gripping makeup primer — the "I hate sunscreen" cure.',
 array['avobenzone','red algae complex'],38.00,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=supergoop%20unseen%20sunscreen"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=supergoop+unseen+sunscreen"}]',
 array['oily','combination','normal'],'am',90),
('boj-relief-sun','Beauty of Joseon','Relief Sun: Rice + Probiotics SPF50+','spf',
 'The K-beauty SPF that broke the internet: serum texture, no cast, real protection.',
 array['rice extract','probiotics','UV filters'],18.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=beauty+of+joseon+relief+sun"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=beauty%20of%20joseon%20relief%20sun"}]',
 array['normal','dry','combination','sensitive'],'am',90),
('cerave-mineral-spf30','CeraVe','Hydrating Mineral Sunscreen SPF 30','spf',
 '100% mineral filters with ceramides — the sting-free pick for reactive or post-procedure skin.',
 array['zinc oxide','titanium dioxide','ceramides'],15.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cerave+hydrating+mineral+sunscreen+spf+30"},{"retailer":"Walgreens","url":"https://www.walgreens.com/search/results.jsp?Ntt=cerave%20mineral%20sunscreen"}]',
 array['sensitive','dry','normal'],'am',90),
('neutrogena-ultra-sheer','Neutrogena','Ultra Sheer Dry-Touch SPF 55','spf',
 'The reliable drugstore workhorse: high SPF, matte dry-touch finish, available everywhere on earth.',
 array['avobenzone','helioplex'],11.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=neutrogena+ultra+sheer+dry+touch+spf+55"},{"retailer":"Walmart","url":"https://www.walmart.com/search?q=neutrogena+ultra+sheer"}]',
 array['normal','oily','combination'],'am',90),

-- ─────────────── Masks & spot care ───────────────
('aztec-clay-mask','Aztec Secret','Indian Healing Clay','mask',
 'Pure bentonite clay that pulls oil and gunk out of congested skin — the deep-clean weekly reset.',
 array['100% bentonite clay'],14.95,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=aztec+secret+indian+healing+clay"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=aztec+healing+clay"}]',
 array['oily','combination'],'pm',70),
('mighty-patch','Hero Cosmetics','Mighty Patch Original','treatment',
 'Hydrocolloid dots that flatten whiteheads overnight and physically stop you from picking.',
 array['hydrocolloid'],12.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=hero+mighty+patch"},{"retailer":"Target","url":"https://www.target.com/s?searchTerm=mighty+patch"}]',
 array['oily','combination','normal','dry','sensitive'],'pm',75),
('cosrx-pimple-patch','COSRX','Acne Pimple Master Patch','treatment',
 'The original K-beauty hydrocolloid patch; thinner edges, daytime-wearable.',
 array['hydrocolloid'],6.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=cosrx+acne+pimple+master+patch"},{"retailer":"Ulta","url":"https://www.ulta.com/search?query=cosrx%20pimple%20patch"}]',
 array['oily','combination','normal','dry','sensitive'],'both',75),
('laneige-water-sleeping-mask','LANEIGE','Water Sleeping Mask','mask',
 'Overnight gel mask that you wash off to noticeably bouncier, brighter morning skin.',
 array['squalane','probiotic complex','glycerin'],29.00,
 '[{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=laneige%20water%20sleeping%20mask"},{"retailer":"Amazon","url":"https://www.amazon.com/s?k=laneige+water+sleeping+mask"}]',
 array['dry','normal','combination'],'pm',70),

-- ─────────────── Supplements ───────────────
('thorne-zinc','Thorne','Zinc Picolinate 30 mg','supplement',
 'Highly absorbable zinc — meta-analyses associate zinc sufficiency with fewer inflammatory acne lesions.',
 array['zinc picolinate 30mg'],17.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=thorne+zinc+picolinate+30mg"},{"retailer":"iHerb","url":"https://www.iherb.com/search?kw=thorne%20zinc%20picolinate"}]',
 array[]::text[],'am',95),
('nordic-omega3','Nordic Naturals','Ultimate Omega 2X','supplement',
 'Concentrated EPA/DHA fish oil; omega-3s support skin barrier lipids and temper inflammatory signaling.',
 array['EPA 1125mg','DHA 875mg'],29.95,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=nordic+naturals+ultimate+omega+2x"},{"retailer":"iHerb","url":"https://www.iherb.com/search?kw=nordic%20naturals%20ultimate%20omega"}]',
 array[]::text[],'am',95),
('now-d3','NOW','Vitamin D3 2000 IU','supplement',
 'Budget-reliable D3 — low vitamin D status repeatedly correlates with eczema and acne severity.',
 array['cholecalciferol 2000 IU'],8.99,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=now+vitamin+d3+2000+iu"},{"retailer":"iHerb","url":"https://www.iherb.com/search?kw=now%20foods%20vitamin%20d3%202000"}]',
 array[]::text[],'am',95),
('vital-collagen','Vital Proteins','Collagen Peptides','supplement',
 'Hydrolyzed collagen; randomized trials report modest improvements in skin elasticity and hydration over 8-12 weeks.',
 array['collagen peptides 20g','hyaluronic acid','vitamin C'],27.00,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=vital+proteins+collagen+peptides"},{"retailer":"Costco","url":"https://www.costco.com/CatalogSearch?keyword=vital%20proteins%20collagen"}]',
 array[]::text[],'am',95),
('to-multi-peptide','The Ordinary','Multi-Peptide + HA Serum','serum',
 'The serum formerly known as Buffet — a broad peptide blend targeting early lines and elasticity.',
 array['Matrixyl 3000','Argirelox','hyaluronic acid'],18.50,
 '[{"retailer":"Amazon","url":"https://www.amazon.com/s?k=the+ordinary+multi+peptide+ha+serum+buffet"},{"retailer":"Sephora","url":"https://www.sephora.com/search?keyword=the%20ordinary%20multi%20peptide"}]',
 array['normal','dry','combination'],'pm',30);

-- ─────────────── Concern mappings ───────────────

insert into public.product_concerns (product_id, concern_slug, relevance, rationale)
select p.id, m.concern_slug, m.relevance, m.rationale
from (values
  -- acne
  ('differin-gel','acne',5,'OTC retinoid with the strongest evidence base for comedonal and inflammatory acne'),
  ('lrp-effaclar-duo','acne',5,'Benzoyl peroxide kills C. acnes directly; micronized formula limits dryness'),
  ('cerave-foaming-cleanser','acne',4,'Non-stripping base cleanser keeps the barrier intact during active treatment'),
  ('mighty-patch','acne',4,'Hydrocolloid flattens whiteheads overnight and prevents picking damage'),
  ('cosrx-pimple-patch','acne',4,'Daytime-wearable spot protection'),
  ('to-salicylic-serum','acne',4,'Leave-on BHA clears pore blockages that become breakouts'),
  ('to-niacinamide','acne',3,'Reduces sebum and calms post-blemish redness'),
  ('boj-glow-serum','acne',3,'Propolis soothes inflamed breakouts while supporting glow'),
  ('eltamd-uv-clear','acne',4,'Acne-safe SPF prevents marks from darkening; niacinamide bonus'),
  ('thorne-zinc','acne',3,'Zinc sufficiency is associated with fewer inflammatory lesions in meta-analyses'),
  ('cerave-pm-lotion','acne',3,'Light non-comedogenic night moisturizer that buffers actives'),
  -- blackheads-congestion
  ('paulas-choice-2-bha','blackheads-congestion',5,'Oil-soluble salicylic acid dissolves blockages inside the pore'),
  ('cerave-sa-cleanser','blackheads-congestion',4,'Daily BHA wash maintains clear pores passively'),
  ('to-salicylic-serum','blackheads-congestion',4,'Budget targeted BHA for congested zones'),
  ('aztec-clay-mask','blackheads-congestion',3,'Weekly bentonite deep-clean pulls out oil and debris'),
  ('to-niacinamide','blackheads-congestion',3,'Regulates the sebum that feeds congestion'),
  ('cosrx-low-ph-cleanser','blackheads-congestion',3,'Low-pH cleansing prevents the over-stripping that worsens congestion'),
  ('cerave-resurfacing-retinol','blackheads-congestion',4,'Retinoids normalize pore-lining turnover, preventing new comedones'),
  -- dryness
  ('cerave-moisturizing-cream','dryness',5,'Ceramide-rich barrier repair; the reference standard for dry skin'),
  ('to-hyaluronic','dryness',4,'Multi-weight humectant pulls water into the skin — apply damp'),
  ('hada-labo-premium-lotion','dryness',4,'Five hyaluronic acid weights in a layerable Japanese lotion'),
  ('cerave-hydrating-cleanser','dryness',4,'Cleans without stripping the lipids dry skin cannot spare'),
  ('cosrx-snail-essence','dryness',3,'Mucin layer locks hydration with a plumping finish'),
  ('weleda-skin-food','dryness',3,'Occlusive rescue for severely flaking patches'),
  ('to-squalane','dryness',3,'Biomimetic lipid top-coat seals everything in'),
  ('laneige-water-sleeping-mask','dryness',3,'Overnight hydration surge for crunch-time recovery'),
  ('lrp-toleriane-cleanser','dryness',3,'Milky no-foam cleansing preserves moisture'),
  -- oiliness
  ('to-niacinamide','oiliness',5,'10% niacinamide + zinc measurably reduces sebum over 4-8 weeks'),
  ('cerave-foaming-cleanser','oiliness',4,'Effective oil removal without rebound-triggering stripping'),
  ('neutrogena-hydro-boost','oiliness',4,'Oil-free water-gel hydration oily skin will actually wear'),
  ('paulas-choice-2-bha','oiliness',4,'Keeps oil from oxidizing into visible congestion'),
  ('aztec-clay-mask','oiliness',3,'Weekly oil purge for shine-prone zones'),
  ('cosrx-low-ph-cleanser','oiliness',3,'Morning cleanse that respects the acid mantle'),
  ('supergoop-unseen','oiliness',3,'Invisible matte-finish SPF that won''t add grease'),
  -- redness-rosacea
  ('to-azelaic','redness-rosacea',5,'Azelaic acid is a first-line topical for rosacea-spectrum redness'),
  ('pc-azelaic-booster','redness-rosacea',4,'Elegant azelaic formula for sensitive budgets that allow it'),
  ('avene-thermal-water','redness-rosacea',3,'Published soothing effect on reactive flushing — keep it cold'),
  ('avene-cicalfate','redness-rosacea',4,'Copper-zinc recovery cream calms angry patches'),
  ('lrp-toleriane-double-repair','redness-rosacea',4,'Barrier repair lowers baseline reactivity'),
  ('cerave-mineral-spf30','redness-rosacea',4,'Mineral filters protect without the sting; UV is a top trigger'),
  ('vanicream-gentle-cleanser','redness-rosacea',4,'Removes every common irritant from the equation'),
  -- hyperpigmentation
  ('to-alpha-arbutin','hyperpigmentation',5,'Tyrosinase inhibitor that fades spots without irritation'),
  ('good-molecules-discoloration','hyperpigmentation',5,'Tranexamic acid + niacinamide for stubborn patches and melasma-adjacent tone'),
  ('timeless-vit-c','hyperpigmentation',4,'L-ascorbic acid brightens existing pigment and blocks new formation'),
  ('to-azelaic','hyperpigmentation',4,'Fades post-inflammatory marks while calming the skin'),
  ('to-glycolic-toner','hyperpigmentation',3,'AHA turnover lifts pigmented surface cells faster'),
  ('eltamd-uv-clear','hyperpigmentation',5,'Without daily SPF every other step is undone by noon'),
  ('skinceuticals-ce-ferulic','hyperpigmentation',4,'The gold-standard antioxidant for tone, if budget allows'),
  -- fine-lines-wrinkles
  ('inkey-retinol','fine-lines-wrinkles',5,'Entry retinol with squalane buffering — the proven collagen play'),
  ('roc-deep-wrinkle-night','fine-lines-wrinkles',4,'Clinically tested drugstore retinol for established creases'),
  ('to-multi-peptide','fine-lines-wrinkles',3,'Peptide signaling support alongside a retinoid'),
  ('skinceuticals-ce-ferulic','fine-lines-wrinkles',4,'Antioxidant defense plus documented photoaging improvement'),
  ('maelove-glow-maker','fine-lines-wrinkles',4,'Vitamin C protects collagen by day'),
  ('olay-regenerist','fine-lines-wrinkles',3,'Peptide-niacinamide moisturizer with strong clinical showings'),
  ('lrp-anthelios-milk','fine-lines-wrinkles',5,'High-SPF daily protection is the most proven anti-aging step'),
  ('roc-retinol-eye','fine-lines-wrinkles',3,'Targeted retinol for crow''s feet'),
  ('vital-collagen','fine-lines-wrinkles',2,'Modest RCT-supported elasticity gains over 8-12 weeks'),
  -- dark-circles
  ('to-caffeine-eye','dark-circles',5,'Vasoconstricting caffeine visibly lightens vascular circles'),
  ('inkey-caffeine-eye','dark-circles',4,'Caffeine + peptides in a cushioned cream base'),
  ('cerave-eye-repair','dark-circles',4,'Thickens and hydrates the thin skin that lets vessels show'),
  ('roc-retinol-eye','dark-circles',3,'Long-term collagen support brightens shadowed hollows'),
  ('boj-relief-sun','dark-circles',3,'Daily SPF prevents periorbital pigment from deepening'),
  -- sensitivity-eczema
  ('vanicream-moisturizing-cream','sensitivity-eczema',5,'NEA-accepted, irritant-free barrier cream'),
  ('cerave-moisturizing-cream','sensitivity-eczema',5,'Ceramide repair in a soak-and-seal friendly tub'),
  ('fab-ultra-repair','sensitivity-eczema',4,'Colloidal oatmeal calms itch on contact'),
  ('lrp-cicaplast-b5','sensitivity-eczema',4,'Panthenol-madecassoside rescue for active flares'),
  ('vanicream-gentle-cleanser','sensitivity-eczema',4,'Cleansing with zero common allergens'),
  ('cetaphil-gentle-cleanser','sensitivity-eczema',3,'The time-tested gentle baseline'),
  ('cerave-mineral-spf30','sensitivity-eczema',4,'Mineral UV protection without chemical-filter sting'),
  ('inkey-pha-toner','sensitivity-eczema',2,'If exfoliation is needed at all, PHA is the gentlest route'),
  -- sun-damage
  ('lrp-anthelios-milk','sun-damage',5,'Stopping further UV damage is step zero'),
  ('eltamd-uv-clear','sun-damage',4,'Daily-wearable protection you will not skip'),
  ('timeless-vit-c','sun-damage',4,'Vitamin C + E + ferulic neutralizes UV-generated free radicals'),
  ('skinceuticals-ce-ferulic','sun-damage',4,'The most-studied antioxidant serum for photoaging'),
  ('to-glycolic-toner','sun-damage',3,'AHA smooths mottled, photo-roughened texture'),
  ('roc-deep-wrinkle-night','sun-damage',3,'Retinol addresses established photoaging at night'),
  ('good-molecules-discoloration','sun-damage',3,'Targets the mottled pigment UV leaves behind'),
  -- enlarged-pores
  ('to-niacinamide','enlarged-pores',5,'Sebum regulation makes pores visibly smaller within weeks'),
  ('paulas-choice-2-bha','enlarged-pores',5,'Empty pores read dramatically smaller than full ones'),
  ('pc-clinical-niacinamide-20','enlarged-pores',4,'Max-strength option for stubborn orange-peel texture'),
  ('cerave-resurfacing-retinol','enlarged-pores',4,'Retinoid collagen support tightens the pore wall over months'),
  ('cosrx-low-ph-cleanser','enlarged-pores',2,'Gentle cleansing avoids the stripping that worsens oil rebound'),
  -- dullness
  ('to-glycolic-toner','dullness',5,'Dissolving dead-cell buildup is the fastest route back to glow'),
  ('to-lactic-acid-10','dullness',4,'Gentler AHA resurfacing with built-in hydration'),
  ('timeless-vit-c','dullness',4,'Brightening antioxidant glow by day'),
  ('cosrx-snail-essence','dullness',4,'Hydration-driven radiance and bounce'),
  ('clinique-moisture-surge','dullness',3,'Plumping water-cream that restores light reflection'),
  ('laneige-water-sleeping-mask','dullness',3,'Wake up brighter — overnight hydration mask'),
  ('yttp-superfood-cleanser','dullness',3,'Antioxidant cleansing base for a glow-focused routine'),
  ('boj-glow-serum','dullness',4,'Propolis glow with breakout-calming side benefits'),
  ('inkey-pha-toner','dullness',3,'Glow for skin too reactive for AHAs')
) as m(slug, concern_slug, relevance, rationale)
join public.products p on p.slug = m.slug;
