-- Glowi seed · nutrition guides (one per concern, with evidence citations)
-- Citation URLs use stable PubMed search links labeled with author/year/journal
-- so they never 404 and never fabricate a PMID. Idempotent.

delete from public.nutrition_guides;

insert into public.nutrition_guides (concern_slug, overview, foods, nutrients, avoid, citations) values

('acne',
 'Diet is not the cause of acne, but randomized trials show it moves the needle: high-glycemic eating spikes insulin and IGF-1, which drive sebum and inflammation. A low-glycemic pattern with adequate zinc and omega-3s is the best-evidenced dietary support for clearer skin.',
 '[{"food":"Steel-cut oats & whole grains","why":"Low-glycemic swaps blunt the insulin spikes linked to breakouts in RCTs","nutrients":["fiber","B vitamins"]},
   {"food":"Fatty fish (salmon, sardines)","why":"EPA/DHA omega-3s lowered inflammatory lesion counts in a 10-week trial","nutrients":["omega-3"]},
   {"food":"Pumpkin seeds & oysters","why":"Top food sources of zinc, which acne patients are disproportionately low in","nutrients":["zinc"]},
   {"food":"Green tea","why":"EGCG reduced sebum and lesions in topical and oral studies","nutrients":["polyphenols"]},
   {"food":"Lentils & beans","why":"Protein + fiber with minimal glycemic load keeps IGF-1 signaling calmer","nutrients":["fiber","protein","zinc"]}]',
 '[{"nutrient":"Zinc","evidence":"Meta-analysis of 14 studies found acne patients have significantly lower serum zinc; supplementation reduced inflammatory papules","dose_note":"30 mg/day elemental zinc with food; avoid >40 mg long-term (copper depletion)"},
   {"nutrient":"Omega-3 (EPA/DHA)","evidence":"10-week RCT (omega-3 or GLA vs control) significantly reduced both inflammatory and non-inflammatory lesions","dose_note":"1-2 g combined EPA/DHA daily"},
   {"nutrient":"Low-glycemic-load pattern","evidence":"12-week RCT showed reduced lesion counts and improved insulin sensitivity vs high-GL diet","dose_note":"Pattern change, not a pill — swap refined carbs for whole-food versions"}]',
 '[{"item":"Skim milk in high volumes","why":"Multiple cohort studies associate skim (more than whole) milk with acne prevalence; whey signaling on IGF-1 is the suspected route"},
   {"item":"High-glycemic snacks & sugary drinks","why":"Direct insulin/IGF-1 driver — the strongest dietary association in trials"},
   {"item":"Whey protein supplements","why":"Case series document acne flares on whey that resolve on discontinuation; swap for plant or casein blends if suspicious"}]',
 '[{"label":"Smith et al., 2007 — Am J Clin Nutr (low-glycemic-load RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=smith+2007+low+glycemic+load+acne"},
   {"label":"Jung et al., 2014 — Acta Derm Venereol (omega-3/GLA RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=jung+2014+omega-3+gamma-linolenic+acne"},
   {"label":"Cervantes et al., 2018 — Dermatologic Therapy (zinc review)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=cervantes+2018+zinc+acne"},
   {"label":"Juhl et al., 2018 — Nutrients (dairy meta-analysis)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=juhl+2018+dairy+acne+meta-analysis"}]'),

('blackheads-congestion',
 'Congestion is driven by sebum quantity and quality. The same insulin-lowering pattern that helps acne reduces oil output, while omega-3 intake shifts sebum composition toward less comedogenic lipid profiles.',
 '[{"food":"Whole grains over refined","why":"Lower glycemic load means less insulin-driven sebum","nutrients":["fiber"]},
   {"food":"Walnuts & flaxseed","why":"Plant omega-3s support healthier sebum lipid balance","nutrients":["ALA omega-3"]},
   {"food":"Carrots & sweet potato","why":"Beta-carotene converts to vitamin A, the nutrient retinoids are derived from","nutrients":["beta-carotene"]},
   {"food":"Water, consistently","why":"Dehydrated skin compensates with thicker, stickier sebum","nutrients":["hydration"]}]',
 '[{"nutrient":"Vitamin A (food-form)","evidence":"Retinoid biology underpins comedone prevention; food-form carotenoids are the safe dietary route (high-dose retinol supplements are not advised unsupervised)","dose_note":"Eat orange/leafy produce daily; do not megadose supplements"},
   {"nutrient":"Omega-3","evidence":"Sebum composition studies show inflammatory lipid shifts correlate with comedogenesis; omega-3 intake counteracts","dose_note":"2 fatty-fish meals weekly or 1 g EPA/DHA daily"},
   {"nutrient":"Zinc","evidence":"Regulates sebocyte activity alongside its anti-inflammatory role","dose_note":"Food-first: seeds, shellfish, legumes"}]',
 '[{"item":"Greasy fast food in excess","why":"Cohort data associate Western dietary patterns with higher comedonal acne prevalence"},
   {"item":"Excess refined sugar","why":"Insulin-driven sebum is stickier and more clog-prone"}]',
 '[{"label":"Melnik, 2015 — Clin Cosmet Investig Dermatol (diet & sebaceous signaling review)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=melnik+2015+linking+diet+acne+metabolomics"},
   {"label":"Downing et al. — sebum lipid composition research","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=sebum+lipid+composition+comedogenesis"}]'),

('dryness',
 'Skin hydration is built from the inside: barrier lipids need essential fatty acids, and trials show both omega-3 supplementation and simply drinking more water (in people who drink little) measurably improve hydration and barrier function.',
 '[{"food":"Salmon & sardines","why":"EPA/DHA incorporate into barrier membranes and reduce transepidermal water loss in trials","nutrients":["omega-3"]},
   {"food":"Avocado & olive oil","why":"Monounsaturated fats and vitamin E support lipid barrier integrity","nutrients":["MUFA","vitamin E"]},
   {"food":"Sunflower seeds","why":"Linoleic acid is a structural requirement of the ceramide barrier — deficiency causes scaling","nutrients":["linoleic acid","vitamin E"]},
   {"food":"2+ liters of water daily","why":"RCT data show extra water intake improves skin hydration specifically in low drinkers","nutrients":["hydration"]},
   {"food":"Soy foods","why":"Isoflavone studies report improved elasticity and reduced dryness in middle-aged women","nutrients":["isoflavones"]}]',
 '[{"nutrient":"Omega-3 (EPA/DHA)","evidence":"12-week supplementation trials show reduced TEWL and improved hydration and roughness scores","dose_note":"1-2 g daily with meals"},
   {"nutrient":"Linoleic acid (omega-6)","evidence":"Essential for ceramide synthesis; deficiency directly causes dry, scaly skin","dose_note":"A small handful of seeds/nuts daily covers it"},
   {"nutrient":"Hyaluronic acid (oral)","evidence":"Multiple Japanese RCTs report improved skin moisture vs placebo after 4-8 weeks","dose_note":"120-240 mg/day if trialing"},
   {"nutrient":"Vitamin E","evidence":"Antioxidant protection of barrier lipids; low status correlates with worse xerosis","dose_note":"Food-first: seeds, nuts, oils"}]',
 '[{"item":"Alcohol","why":"Acts as a diuretic and vasodilator — classic next-morning dehydrated skin"},
   {"item":"Very low-fat dieting","why":"The lipid barrier is literally built from dietary fat; chronic ultra-low-fat intake shows in the skin first"}]',
 '[{"label":"Palma et al., 2015 — Clin Cosmet Investig Dermatol (water intake RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=palma+2015+dietary+water+skin+hydration"},
   {"label":"Kawada et al., 2014 — Nutrition Journal (oral hyaluronan review)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=kawada+2014+ingested+hyaluronan+skin+moisturizes"},
   {"label":"Barcelos et al. — omega-3 and skin barrier studies","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=omega-3+supplementation+transepidermal+water+loss"}]'),

('oiliness',
 'Sebum production responds to hormones and insulin signaling. The clearest dietary levers are glycemic load and dairy signaling; green tea adds a modest, measurable sebum-lowering effect.',
 '[{"food":"Low-glycemic staples (legumes, oats, vegetables)","why":"Insulin and IGF-1 are direct throttles on sebocyte output","nutrients":["fiber"]},
   {"food":"Green tea (2-3 cups)","why":"EGCG modulates sebum production in clinical studies","nutrients":["EGCG","polyphenols"]},
   {"food":"Pumpkin seeds","why":"Zinc participates in androgen metabolism feeding oil production","nutrients":["zinc"]},
   {"food":"Colorful produce","why":"Antioxidants temper oxidation of squalene — oxidized sebum is what clogs","nutrients":["carotenoids","vitamin C"]}]',
 '[{"nutrient":"Low-glycemic pattern","evidence":"RCT participants on low-GL diets showed reduced sebum output alongside lesion improvements","dose_note":"The single best-evidenced intervention for oil"},
   {"nutrient":"EGCG (green tea)","evidence":"Clinical studies show measurably reduced sebum after topical and oral green tea catechins","dose_note":"2-3 cups daily; benefits accrue over weeks"},
   {"nutrient":"Zinc","evidence":"Modulates 5α-reductase activity in androgen-driven sebum production","dose_note":"Food-first; 30 mg supplemental ceiling"}]',
 '[{"item":"Sugary drinks","why":"The fastest route to the insulin spike that turns oil glands up"},
   {"item":"Skim-milk-heavy diets","why":"Dairy hormonal signaling is associated with sebaceous activity in cohort data"}]',
 '[{"label":"Smith et al., 2007 — Am J Clin Nutr (low-GL diet, sebum substudy)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=smith+2007+glycemic+load+sebum"},
   {"label":"Saric et al., 2016 — Antioxidants (green tea & acne review)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=saric+2016+green+tea+acne"}]'),

('redness-rosacea',
 'Rosacea-spectrum redness has a strong gut-skin and trigger component. Survey data from the National Rosacea Society consistently identify alcohol, spicy food, and hot drinks as top flush triggers, while emerging trial data support omega-3s and gut-supportive eating.',
 '[{"food":"Fatty fish","why":"Omega-3s reduced ocular rosacea symptoms in an RCT and temper systemic inflammation","nutrients":["omega-3"]},
   {"food":"Fermented foods (yogurt, kefir, kimchi)","why":"Small-intestinal bacterial overgrowth is over-represented in rosacea; gut support correlates with calmer skin","nutrients":["probiotics"]},
   {"food":"Fiber-rich vegetables & oats","why":"Prebiotic fiber feeds the gut flora implicated in the gut-skin axis","nutrients":["prebiotic fiber"]},
   {"food":"Cool or iced drinks","why":"Heat itself — not just caffeine — is the flush trigger in hot beverages","nutrients":["hydration"]}]',
 '[{"nutrient":"Omega-3 (EPA/DHA)","evidence":"RCT in ocular rosacea showed significant symptom improvement vs placebo over 6 months","dose_note":"1-2 g daily"},
   {"nutrient":"Probiotics","evidence":"SIBO eradication studies report rosacea improvement; probiotic support is a reasonable low-risk adjunct","dose_note":"Daily fermented food or a multi-strain product"},
   {"nutrient":"Zinc","evidence":"Mixed but suggestive trial data on rosacea severity scores","dose_note":"Food-first approach preferred"}]',
 '[{"item":"Alcohol (especially red wine)","why":"Top self-reported trigger in NRS surveys — vasodilation plus histamine"},
   {"item":"Spicy food (capsaicin)","why":"Directly activates the same heat receptors that drive flushing"},
   {"item":"Very hot drinks","why":"Thermal flush trigger; let coffee and tea cool slightly"},
   {"item":"High-histamine foods (aged cheese, cured meat)","why":"Histamine intolerance overlaps with flush-prone profiles"}]',
 '[{"label":"Bhargava et al., 2013 — Int J Ophthalmol (omega-3 ocular rosacea RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=bhargava+omega-3+dry+eye+rosacea"},
   {"label":"Parodi et al., 2008 — Clin Gastroenterol Hepatol (SIBO eradication & rosacea)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=parodi+2008+small+intestinal+bacterial+overgrowth+rosacea"},
   {"label":"National Rosacea Society trigger surveys","source":"NRS","url":"https://www.rosacea.org/patients/rosacea-triggers/rosacea-triggers-survey"}]'),

('hyperpigmentation',
 'Pigment is made by tyrosinase, an enzyme that antioxidant nutrients demonstrably modulate. Vitamin C status, polyphenols, and photoprotective carotenoids all influence how much new pigment forms — especially alongside daily SPF.',
 '[{"food":"Citrus, kiwi, bell peppers","why":"Vitamin C is a cofactor-level tyrosinase inhibitor and collagen protector","nutrients":["vitamin C"]},
   {"food":"Tomato paste (cooked)","why":"Lycopene provided measurable UV photoprotection in controlled trials — less UV, less pigment","nutrients":["lycopene"]},
   {"food":"Green tea","why":"Catechins reduce UV-induced pigmentation in supplementation studies","nutrients":["EGCG"]},
   {"food":"Pomegranate","why":"Ellagic acid studies report reduced UV-induced pigment formation","nutrients":["ellagic acid"]},
   {"food":"Soy foods","why":"Isoflavones interfere with melanosome transfer pathways","nutrients":["isoflavones"]}]',
 '[{"nutrient":"Vitamin C","evidence":"Tyrosinase inhibition is mechanistically established; higher dietary intake correlates with better photoaging scores in NHANES-style data","dose_note":"Aim for vitamin C-rich produce at most meals"},
   {"nutrient":"Lycopene","evidence":"RCT: 10 weeks of tomato paste reduced UV-induced erythema ~40% vs control","dose_note":"Cooked tomato products absorb far better than raw"},
   {"nutrient":"Polyphenols (green tea, pomegranate)","evidence":"Human studies show reduced UV pigment response after sustained intake","dose_note":"Daily, sustained — single doses do nothing"}]',
 '[{"item":"Unprotected sun on treated skin","why":"Not a food, but the dietary guide is void without SPF — UV re-darkens every fading spot"},
   {"item":"Excess alcohol","why":"Impairs antioxidant status and worsens post-inflammatory healing"}]',
 '[{"label":"Rizwan et al., 2011 — Br J Dermatol (tomato paste photoprotection RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=rizwan+2011+tomato+paste+lycopene+photoprotection"},
   {"label":"Cosgrove et al., 2007 — Am J Clin Nutr (nutrient intake & skin aging)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=cosgrove+2007+nutrient+intakes+skin-aging+appearance"},
   {"label":"Heinrich et al., 2011 — J Nutr (green tea polyphenols & skin)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=heinrich+2011+green+tea+polyphenols+photoprotection"}]'),

('fine-lines-wrinkles',
 'Collagen is a protein you build and defend with diet. Human data link vitamin C and linoleic acid intake to fewer wrinkles, collagen peptide RCTs show modest elasticity gains, and photoprotective carotenoids slow the UV damage behind most visible aging.',
 '[{"food":"Citrus & berries","why":"Vitamin C is required for collagen cross-linking; higher intake associates with fewer wrinkles","nutrients":["vitamin C"]},
   {"food":"Bone broth / collagen-rich cuts or peptides","why":"Hydrolyzed collagen RCTs report improved elasticity and hydration at 8-12 weeks","nutrients":["collagen peptides","glycine","proline"]},
   {"food":"Fatty fish","why":"Omega-3 membranes resist inflammatory collagen breakdown","nutrients":["omega-3"]},
   {"food":"Cooked tomatoes & carrots","why":"Carotenoid photoprotection reduces the UV load that degrades collagen","nutrients":["lycopene","beta-carotene"]},
   {"food":"Nuts & seeds","why":"Vitamin E + linoleic acid intake correlates with better skin-aging scores","nutrients":["vitamin E","linoleic acid"]}]',
 '[{"nutrient":"Vitamin C","evidence":"NHANES analysis: higher vitamin C intake associated with lower likelihood of wrinkled appearance; essential cofactor for prolyl hydroxylase in collagen synthesis","dose_note":"Produce-first; supplements only fill gaps"},
   {"nutrient":"Collagen peptides","evidence":"Multiple placebo-controlled RCTs report improved elasticity/hydration; effect size modest but consistent","dose_note":"2.5-10 g daily for 8-12 weeks to evaluate"},
   {"nutrient":"Carotenoids","evidence":"Meta-analysis: beta-carotene supplementation provides measurable (sub-SPF) photoprotection after 10+ weeks","dose_note":"Food-form preferred; smokers should avoid high-dose beta-carotene supplements"}]',
 '[{"item":"Added sugar","why":"Glycation cross-links stiffen collagen (AGEs) — documented in skin biopsy studies"},
   {"item":"Smoking (and vaping nicotine)","why":"The single most powerful dietary-adjacent accelerant of facial aging in twin studies"},
   {"item":"Charred, high-heat-cooked meats","why":"Dietary AGE load adds to the glycation burden"}]',
 '[{"label":"Cosgrove et al., 2007 — Am J Clin Nutr (nutrient intake & skin aging)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=cosgrove+2007+nutrient+intakes+skin-aging+appearance"},
   {"label":"Proksch et al., 2014 — Skin Pharmacol Physiol (collagen peptide RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=proksch+2014+collagen+peptide+skin+elasticity"},
   {"label":"Köpcke & Krutmann, 2008 — Photochem Photobiol (beta-carotene meta-analysis)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=kopcke+krutmann+2008+carotene+sunburn+meta-analysis"}]'),

('dark-circles',
 'Under-eye darkness has nutritional contributors that are routinely missed: iron deficiency and poor sleep both show up under the eyes before anywhere else, and fluid-retention from sodium amplifies morning shadowing.',
 '[{"food":"Lean red meat, lentils, spinach","why":"Iron deficiency (with or without anemia) produces periorbital pallor and shadow","nutrients":["iron"]},
   {"food":"Vitamin C alongside iron sources","why":"Triples non-heme iron absorption from plant foods","nutrients":["vitamin C"]},
   {"food":"Potassium-rich produce (banana, potato, beans)","why":"Counterbalances sodium-driven fluid retention and morning puffiness","nutrients":["potassium"]},
   {"food":"Water through the day","why":"Dehydration sinks the under-eye area, deepening shadows","nutrients":["hydration"]}]',
 '[{"nutrient":"Iron","evidence":"Periorbital darkening is a recognized clinical sign of iron deficiency; correction improves appearance over months","dose_note":"Test ferritin before supplementing — excess iron is harmful"},
   {"nutrient":"Vitamin K","evidence":"Limited but suggestive topical/dietary data on vascular show-through","dose_note":"Leafy greens daily; no megadosing"},
   {"nutrient":"Sleep (the honorary nutrient)","evidence":"Controlled sleep-restriction studies show observers reliably rate short-sleepers as having darker circles","dose_note":"7-9 hours; consistency beats duration"}]',
 '[{"item":"Late-evening sodium bombs","why":"Overnight fluid retention puffs the lower lid, casting shadow"},
   {"item":"Alcohol before bed","why":"Fragments sleep and dehydrates — the double hit visible by morning"}]',
 '[{"label":"Axelsson et al., 2010 — BMJ (sleep deprivation & perceived appearance)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=axelsson+2010+beauty+sleep+facial+appearance"},
   {"label":"Periorbital hyperpigmentation reviews (etiology incl. anemia)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=periorbital+hyperpigmentation+etiology+review"}]'),

('sensitivity-eczema',
 'Eczema-prone skin tracks the gut and immune system closely. Probiotic meta-analyses show modest symptom benefits, vitamin D status correlates with severity, and omega-3s support the barrier lipids that reactive skin lacks.',
 '[{"food":"Yogurt/kefir with live cultures","why":"Probiotic meta-analyses report modest SCORAD improvements in adults and children","nutrients":["probiotics"]},
   {"food":"Fatty fish","why":"Omega-3s shift the inflammatory tone implicated in flares","nutrients":["omega-3"]},
   {"food":"Eggs & fortified dairy (if tolerated)","why":"Vitamin D status correlates inversely with eczema severity; deficiency is common","nutrients":["vitamin D"]},
   {"food":"Oats (eaten, not just applied)","why":"Beta-glucan fiber supports the gut flora linked to immune calm","nutrients":["beta-glucan"]}]',
 '[{"nutrient":"Vitamin D","evidence":"RCTs of supplementation in deficient eczema patients show severity score improvements; winter flares track low status","dose_note":"1000-2000 IU/day typical; test if possible"},
   {"nutrient":"Probiotics","evidence":"Meta-analyses show modest but real SCORAD reductions, strongest for multi-strain Lactobacillus/Bifidobacterium","dose_note":"8+ week trial to judge"},
   {"nutrient":"Omega-3","evidence":"Barrier lipid support; small trials report itch reduction","dose_note":"1-2 g EPA/DHA daily"}]',
 '[{"item":"Personal trigger foods — identified properly","why":"True food-triggered eczema exists but is over-self-diagnosed; eliminate systematically (2-week single eliminations), not wholesale"},
   {"item":"Alcohol during flares","why":"Vasodilation intensifies itch and disrupts the sleep that healing needs"},
   {"item":"Ultra-processed dietary patterns","why":"Associated with higher atopy prevalence in cohort studies"}]',
 '[{"label":"Kim et al., 2014 — Ann Allergy Asthma Immunol (probiotics & AD meta-analysis)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=kim+2014+probiotics+atopic+dermatitis+meta-analysis"},
   {"label":"Camargo et al., 2014 — J Allergy Clin Immunol (vitamin D RCT, winter eczema)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=camargo+2014+vitamin+d+winter-related+atopic+dermatitis"},
   {"label":"Palmer, 2020+ — diet & eczema reviews","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=diet+atopic+dermatitis+adults+review"}]'),

('sun-damage',
 'No food replaces sunscreen, but the photoprotection literature is real: carotenoids, green tea polyphenols, and omega-3s each measurably raise the skin''s internal UV threshold over 8-12 weeks of consistent intake.',
 '[{"food":"Cooked tomato products","why":"The flagship RCT: 10 weeks of tomato paste cut UV-induced redness ~40%","nutrients":["lycopene"]},
   {"food":"Carrots, sweet potato, leafy greens","why":"Beta-carotene accumulates in skin and provides meta-analysis-confirmed photoprotection","nutrients":["beta-carotene"]},
   {"food":"Green tea (daily)","why":"12-week catechin studies show reduced UV erythema and better skin structure","nutrients":["EGCG"]},
   {"food":"Fatty fish","why":"Omega-3s raise the UV dose required to burn and reduce UV immune suppression","nutrients":["omega-3"]},
   {"food":"Dark chocolate (high-flavanol)","why":"High-flavanol cocoa doubled minimal erythema dose in a 12-week trial","nutrients":["cocoa flavanols"]}]',
 '[{"nutrient":"Lycopene","evidence":"Multiple controlled feeding studies show significant erythema reduction; effect builds over 10+ weeks","dose_note":"Tomato paste/sauce several times weekly; fat improves absorption"},
   {"nutrient":"Beta-carotene","evidence":"Meta-analysis of 7 studies confirms photoprotection after minimum 10 weeks","dose_note":"Food-form preferred; smokers must avoid high-dose supplements (lung cancer risk in trials)"},
   {"nutrient":"Polyphenols (green tea, cocoa)","evidence":"RCTs show increased minimal erythema dose and improved dermal blood flow","dose_note":"Consistency is everything — these are cumulative effects"}]',
 '[{"item":"Treating any food as a sunscreen substitute","why":"Internal photoprotection equals roughly SPF 2-4. It is a supplement to SPF, never a replacement"},
   {"item":"Alcohol at the beach","why":"Studies show alcohol consumption lowers the UV dose needed to burn"}]',
 '[{"label":"Rizwan et al., 2011 — Br J Dermatol (tomato paste RCT)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=rizwan+2011+tomato+paste+lycopene+photoprotection"},
   {"label":"Köpcke & Krutmann, 2008 — Photochem Photobiol (beta-carotene meta-analysis)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=kopcke+krutmann+2008+carotene+sunburn+meta-analysis"},
   {"label":"Heinrich et al., 2006/2011 — J Nutr (cocoa flavanols; green tea & UV)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=heinrich+cocoa+flavanols+photoprotection"}]'),

('enlarged-pores',
 'Pore visibility follows sebum output and the collagen scaffolding around each pore. The diet levers are therefore the oil-control playbook (glycemic load) plus the collagen-defense playbook (vitamin C, low sugar).',
 '[{"food":"Low-glycemic staples","why":"Less insulin-driven sebum means pores carry less load and read smaller","nutrients":["fiber"]},
   {"food":"Citrus & peppers","why":"Vitamin C maintains the collagen wall that holds pores tight","nutrients":["vitamin C"]},
   {"food":"Green tea","why":"Sebum-modulating catechins, the same mechanism that helps oiliness","nutrients":["EGCG"]},
   {"food":"Fatty fish","why":"Anti-inflammatory support for the perifollicular structure","nutrients":["omega-3"]}]',
 '[{"nutrient":"Low-glycemic pattern","evidence":"Sebum reduction documented in low-GL RCTs translates directly to pore appearance","dose_note":"The pore version of oil control"},
   {"nutrient":"Vitamin C","evidence":"Collagen synthesis cofactor — the structural side of pore visibility","dose_note":"Produce at every meal"},
   {"nutrient":"Avoid AGE load (sugar)","evidence":"Glycation stiffens and weakens collagen, including the pore wall","dose_note":"Treat added sugar as a structural issue, not just calories"}]',
 '[{"item":"Sugar-heavy diets","why":"Double hit: more sebum now, weaker pore-wall collagen later"},
   {"item":"Crash diets","why":"Rapid weight cycling reduces dermal support and elasticity"}]',
 '[{"label":"Smith et al., 2007 — Am J Clin Nutr (low-GL & sebum)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=smith+2007+glycemic+load+sebum"},
   {"label":"Danby, 2010 — Clin Dermatol (nutrition & aging skin incl. glycation)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=danby+2010+nutrition+aging+skin+glycation"}]'),

('dullness',
 'Radiance is hydration plus micro-circulation plus turnover — all three respond to diet within weeks. Carotenoid intake even shifts measured skin tone toward the golden glow observers rate as healthier.',
 '[{"food":"Carrots, tomatoes, leafy greens","why":"Carotenoids deposit in skin and measurably improve perceived healthy glow within 6 weeks","nutrients":["carotenoids"]},
   {"food":"Citrus & berries","why":"Vitamin C drives the collagen and antioxidant systems behind surface light reflection","nutrients":["vitamin C"]},
   {"food":"Water + electrolyte balance","why":"Plump, hydrated skin reflects light evenly — the literal mechanism of glow","nutrients":["hydration"]},
   {"food":"Beets & nitrate greens","why":"Dietary nitrate supports the micro-circulation that flushes skin with color","nutrients":["nitrates"]},
   {"food":"Kiwi","why":"One of the densest vitamin C foods per calorie, with sleep-quality side benefits in small trials","nutrients":["vitamin C"]}]',
 '[{"nutrient":"Carotenoids","evidence":"Controlled studies show 6 weeks of increased fruit/veg intake produces skin-tone changes observers rate as healthier and more attractive","dose_note":"3-5 colorful servings daily"},
   {"nutrient":"Vitamin C","evidence":"Cofactor for collagen and regenerator of vitamin E — the antioxidant network behind radiance","dose_note":"Spread through the day; it is water-soluble"},
   {"nutrient":"Hydration","evidence":"Water-intake RCT showed improved skin hydration in low drinkers within 4 weeks","dose_note":"~2 L baseline, more with exercise"}]',
 '[{"item":"Alcohol","why":"Tomorrow''s grey, dehydrated cast is largely last night''s drinks"},
   {"item":"Ultra-processed, produce-free stretches","why":"Carotenoid skin stores deplete visibly within weeks"}]',
 '[{"label":"Whitehead et al., 2012 — PLoS ONE (fruit/veg consumption & skin color)","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=whitehead+2012+fruit+vegetable+skin+color+appearance"},
   {"label":"Palma et al., 2015 — water intake & skin hydration","source":"PubMed","url":"https://pubmed.ncbi.nlm.nih.gov/?term=palma+2015+dietary+water+skin+hydration"}]');
